// Alle schermteksten van de Analysepagina, plus de kleine invulhulp en de
// ernst-stijlen die erbij horen.
//
// Stonden bovenin AnalysePage.jsx en besloegen daar bijna achthonderd regels,
// waardoor je door de hele woordenlijst moest scrollen voordat je bij de eerste
// component was. Let op: scripts/check-i18n.mjs kijkt hier niet in -- deze
// lijsten moeten met de hand gelijk gehouden worden (nl en en).

// Analysepagina: alles wat de tool over ALLE data kan zeggen — metrieken,
// trends, constateringen, rapporten — bewust zo volledig mogelijk, zodat het
// team kan kiezen wat weg mag i.p.v. wat erbij moet. Elke kaart draagt zijn
// eigen uitleg (regel of formule in gewone taal): geen black box.
// Teksten staan hier lokaal (zelfde afweging als ADMIN_PAGE_CONFIG in
// SettingsPanel): ruim honderd sleutels voor één pagina zouden strings.js
// onleesbaar maken.
export const TEKST = {
  nl: {
    titel: 'Analyse',
    intro: 'Alles hieronder komt rechtstreeks uit de data in deze tool en is per kaart uitlegbaar. Trends en doorlooptijden komen uit de wijzigingshistorie van de dependencies.',
    alleTeams: 'Alle teams',
    teamFilter: 'Team',
    periode: 'Periode',
    weken: '{{n}} weken',
    vsToen: 't.o.v. 30 dagen geleden',
    geenData: 'Geen gegevens.',
    toon: 'Toon {{n}} records',
    verberg: 'Verberg',
    dagen: '{{n}} dagen',
    dag: 'dagen',
    team: 'Team',
    titelKol: 'Titel',
    risico: 'Risico',
    aantal: 'Aantal',
    gesloten: 'gesloten',
    geslotenKop: 'Gesloten',
    categorie: 'Categorie',
    escalatie: '{{n}} escalatie',
    escalatiesN: '{{n}} escalaties',
    kindInput: 'Input',
    kindOutput: 'Output',
    sRapport: 'Rapport',
    sWaarschuwingen: 'Waarschuwingen',
    rapportUitleg: 'Lopende tekst uit dezelfde cijfers: samenvatting, ontwikkeling, risico, teams, keten, applicaties, datakwaliteit en aanbevelingen. Volgt het teamfilter.',
    rapportKopieer: 'Kopieer rapport',
    rapportDownload: 'Download',
    rapportDownloadTitel: 'Download het rapport als markdown-bestand',
    rapportGekopieerd: 'Gekopieerd',
    rapportTitel: 'Rapport dependencies',
    waarschuwingenUitleg: 'Eén zin per geval, gesorteerd op ernst en zwaarte. Klik om het detail of de teampagina te openen.',
    waarschuwingenGeen: 'Geen waarschuwingen.',
    toonAlle: 'Toon alle {{n}}',
    toonMinder: 'Toon minder',
    navTabs: 'Onderdelen',
    tabOverzicht: 'Overzicht',
    tabSignalen: 'Signalen',
    tabTrends: 'Trends',
    tabRisico: 'Risico',
    tabKeten: 'Keten en proces',
    tabData: 'Data en beheer',
    cVerslechterd: 'In 30 dagen gestegen naar Hoog of Kritiek',
    cTeruggevallen: 'Mitigatie hield geen stand',
    cSluimerend: 'Sluimerend: hoog of kritiek, ouder dan een half jaar, zonder afspraak',
    cGeaccepteerdHoog: 'Geparkeerd (geaccepteerd) maar Hoog of Kritiek',
    cGemitigeerdNietGesloten: 'Al meer dan 90 dagen gemitigeerd maar niet afgesloten',
    cHeropend: 'Heropend na sluiting',
    cBacklogGroei: 'De voorraad groeit: meer nieuw dan gesloten',
    cKetenRisicoHoog: 'Veel blokkerend of hoog risico bij directe toeleveranciers: {{teams}}',
    cWederzijds: 'Wederzijdse afhankelijkheid tussen teams: {{paren}}',
    cGedeeldeApp: 'Applicatie via de keten gekoppeld aan meerdere andere teams: {{apps}}',
    cSlapendTeam: 'Al 60 dagen niets geregistreerd: {{teams}}',
    cDubbeleRegistratie: 'Zelfde dependency door meer teams apart vastgelegd',
    kVerandering: 'Verslechterd en verbeterd (30 dagen)',
    uVerandering: 'Score van 30 dagen geleden (replay) tegenover nu; alleen dependencies die toen al bestonden.',
    verslechterd: 'Verslechterd',
    verbeterd: 'Verbeterd',
    kProjectie: 'Projectie',
    uProjectie: 'Lineaire doortrekking van de laatste 13 weken: gemiddeld nieuw en gesloten per week. Geen model, alleen tempo.',
    pNieuwPerWeek: 'Nieuw per week',
    pGeslotenPerWeek: 'Gesloten per week',
    pNetto: 'Netto per week',
    pOverHorizon: 'Open over 13 weken',
    pWekenTotLeeg: 'Weken tot voorraad leeg',
    kOvergangen: 'Statusovergangen',
    uOvergangen: 'Alle statuswijzigingen uit de historie, van en naar. Daaronder: mitigaties die niet standhielden en heropeningen.',
    van: 'Van',
    naar: 'Naar',
    teruggevallen: 'Mitigatie hield geen stand',
    heropend: 'Heropend',
    kLeeftijd: 'Leeftijdsverdeling',
    uLeeftijd: 'Dagen sinds aanmaak van de open dependencies, in klassen; gemiddelde en mediaan per team.',
    gemiddeld: 'Gem.',
    mediaan: 'Mediaan',
    totaal: 'Totaal',
    kLevensloop: 'Sluimerend, geparkeerd en niet afgesloten',
    uLevensloop: 'Sluimerend: bekend risico op Hoog of Kritiek, ouder dan 180 dagen, zonder afspraak. Geparkeerd: geaccepteerd maar Hoog of Kritiek. Niet afgesloten: langer dan 90 dagen gemitigeerd.',
    sluimerend: 'Sluimerend',
    geparkeerdHoog: 'Geparkeerd maar hoog',
    nietAfgesloten: 'Gemitigeerd, niet afgesloten',
    kScorekaart: 'Teamscorekaart',
    uScorekaart: 'Alle teams naast elkaar, ongeacht het teamfilter; de onderste rij is het gemiddelde per team. Δ30 = verandering in open dependencies t.o.v. 30 dagen geleden.',
    open: 'Open',
    hoogPlus: 'Hoog+',
    kritiekKort: 'Kritiek',
    gemScoreKort: 'Gem. score',
    verouderdPct: 'Verouderd',
    afspraakPct: 'Met afspraak',
    delta30: 'Δ30',
    gesloten90: 'Gesloten 90d',
    kennisScore: 'Kennis',
    gemiddeldPerTeam: 'Gemiddeld per team',
    kPareto: 'Concentratie (top 3)',
    uPareto: 'Welk aandeel de drie grootste voor hun rekening nemen, en per team de grootste categorie.',
    top3Partijen: 'Partijen',
    top3Categorieen: 'Categorieën',
    top3Teams: 'Teams',
    topCategoriePerTeam: 'Grootste categorie per team',
    vanTotaal: 'van {{n}}',
    kKetenRisico: 'Ketenrisico stroomopwaarts en -afwaarts',
    uKetenRisico: 'Via geaccepteerde koppelingen: van hoeveel teams een team input krijgt (direct en verder), hoeveel blokkerende en hoge dependencies die directe toeleveranciers (TL) open hebben, en hoeveel teams het zelf stroomafwaarts raakt. Bevestigd = eigen dependencies die zo’n toeleverancier als veroorzaker noemen.',
    direct: 'Direct',
    stroomop: 'Stroomop',
    stroomaf: 'Stroomaf',
    blokTL: 'Blokkerend bij TL',
    hoogTL: 'Hoog+ bij TL',
    bevestigd: 'Bevestigd',
    kWederzijds: 'Wederzijdse afhankelijkheden',
    uWederzijds: 'Teamparen die dependencies op elkaar hebben geregistreerd.',
    geenWederzijds: 'Geen wederzijdse afhankelijkheden.',
    kKaart: 'Kaartvolledigheid per team',
    uKaart: 'Inputs verklaard (koppeling of partij), outputs afgenomen of extern, applicaties met ingevuld uitvalrisico, koppelingen met punten. Volledigheid = gemiddelde van die percentages.',
    inputsVerklaard: 'Inputs verklaard',
    outputsVerklaard: 'Outputs verklaard',
    appsDetail: 'Apps met detail',
    koppelingenPunten: 'Koppelingen met punten',
    notities: 'Notities',
    volledigheid: 'Volledigheid',
    kGedeeld: 'Gedeelde applicaties',
    uGedeeld: 'Applicaties die via een geaccepteerde ketenkoppeling (output met applicatie naar input met applicatie) aan andere teams hangen, met de eigen dependencies erop.',
    andereTeams: 'Andere teams',
    geenGedeeld: 'Geen applicaties met ketenkoppelingen naar andere teams.',
    kSlapend: 'Laatste activiteit per team',
    uSlapend: 'Laatste logregel per team; meer dan 60 dagen stil geldt als slapend.',
    laatsteActiviteit: 'Laatste activiteit',
    dagenStil: 'Dagen stil',
    slapend: 'Slapend',
    kDuplicaten: 'Dubbele registraties',
    uDuplicaten: 'Groepen dependencies die door meer dan één team apart zijn vastgelegd (dedup-groep).',
    geenDuplicaten: 'Geen dubbele registraties.',
    nooit: 'nooit',
    // secties
    sOverzicht: 'Overzicht',
    sConstateringen: 'Constateringen',
    sTrends: 'Trends',
    sRisico: 'Risico en urgentie',
    sVerdeling: 'Verdelingen en hotspots',
    sConcentratie: 'Concentratie en hubs',
    sKeten: 'Keten',
    sProces: 'Applicaties en ontwikkelproces',
    sFlowverlies: 'Flowverlies',
    sDoorloop: 'Doorlooptijden',
    sKwaliteit: 'Datakwaliteit',
    sBeheer: 'Beheer en registratie',
    // tegels
    tOpen: 'Open dependencies',
    tKritiek: 'Kritiek',
    tHoog: 'Hoog of kritiek',
    tBlokkerend: 'Actief blokkerend',
    tVerouderd: 'Verouderd (>90 dagen niet bijgewerkt)',
    tAfspraak: 'Open zonder actie-afspraak',
    tGeaccepteerd: 'Geaccepteerd (geparkeerd)',
    tGesloten90: 'Gesloten in de laatste 90 dagen',
    tNieuw30: 'Nieuw in de laatste 30 dagen',
    tMitigatie: 'Gem. dagen tot mitigatie',
    tScore: 'Gemiddelde risicoscore',
    tVerzoeken: 'Koppelingsverzoeken open',
    // constateringen
    ernstHoog: 'hoog',
    ernstMidden: 'midden',
    ernstLaag: 'laag',
    cKritiekZonderAfspraak: 'Kritieke dependencies zonder actie-afspraak',
    cHardeDeadlineZonderAfspraak: 'Harde deadline zonder actie-afspraak',
    cBlokkerendVerouderd: 'Actief blokkerend maar al meer dan 90 dagen niet bijgewerkt',
    cLangBlokkerend: 'Al meer dan 60 dagen onafgebroken blokkerend',
    cHoogVerouderd: 'Hoog risico, geen actie-afspraak én verouderd',
    cStilRisico: 'Stille risico’s: laag of gemiddeld risico, maar hoog flowverlies',
    cPartijGeweigerd: 'Verwijzing naar een geweigerde partij',
    cPartijInAfwachting: 'Verwijzing naar een partij die nog niet is goedgekeurd',
    cPartijHub: 'Partij raakt de helft of meer van de teams: {{partijen}}',
    cVerzoekOud: 'Koppelingsverzoeken die langer dan twee weken openstaan',
    cDepZonderKoppeling: 'Dependency op een team zonder ketenkoppeling met dat team',
    cSpofZonderDetail: 'Zwaar belaste applicatie zonder ingevuld risico bij uitval: {{apps}}',
    cTeamVerouderd: 'Meer dan 40% van de dependencies verouderd bij: {{teams}}',
    cKennisBusFactor: 'Kennisconcentratie met hoog risico bij: {{teams}}',
    cFaseZonderCapaciteit: 'Werkstap met dependencies maar zonder capaciteit: {{fasen}}',
    cReviewOud: 'Aanmeldingen die langer dan een week op review wachten',
    cGemitigeerdZonderTekst: 'Gemitigeerd zonder beschreven mitigatie',
    cProfielOnvolledig: 'Profiel onvolledig (wachttijd, deadline of oplosbaarheid leeg)',
    cGeen: 'Geen constateringen. Alle regels zijn schoon.',
    // trends
    kOpenStatus: 'Open dependencies per status',
    uOpenStatus: 'Toestand per week, teruggerekend uit de historie: een dependency telt mee vanaf aanmaak tot sluiting, met de status van dat moment.',
    kOpenNiveau: 'Open dependencies per risiconiveau',
    uOpenNiveau: 'Zelfde replay, maar de risicoscore van dat moment (impact × frequentie + statuscorrectie).',
    kNieuwGesloten: 'Nieuw en gesloten per week',
    uNieuwGesloten: 'Aanmaakdatum en sluitdatum per week. Meer nieuw dan gesloten betekent een groeiende voorraad.',
    kScore: 'Som van de risicoscores',
    uScore: 'Alle open scores opgeteld: één getal voor de totale risicodruk.',
    // risico
    kKwadranten: 'Kwadranten: flowverlies tegen oplosbaarheid',
    uKwadranten: 'Quick win = veel verlies, zelf oplosbaar. Opschalen = veel verlies, buiten het team. Opruimen = weinig verlies, zelf oplosbaar. Accepteren = weinig verlies, buiten het team.',
    qQuickWin: 'Quick wins',
    qOpschalen: 'Opschalen',
    qOpruimen: 'Opruimen',
    qAccepteren: 'Accepteren',
    qOnvolledig: 'Profiel onvolledig',
    kStil: 'Stille risico’s',
    uStil: 'Risico Laag of Gemiddeld, flowverlies Hoog of Kritiek. Precies de lijst die de risicoscore niet bovenaan zet.',
    kQuick: 'Quick wins',
    uQuick: 'Oplosbaar door één of meer teamleden én flowverlies minstens Gemiddeld.',
    kDeadlines: 'Deadlines',
    uDeadlines: 'Vaste en harde deadlines, harde eerst. Een rode markering: zonder actie-afspraak.',
    kGemitigeerdHoog: 'Gemitigeerd maar nog steeds Hoog',
    uGemitigeerdHoog: 'De basis (impact × frequentie) blijft zwaar, ook met de correctie van min 2.',
    kAcuut: 'Acuut en chronisch',
    uAcuut: 'Acuut: aangemaakt in de laatste 30 dagen. Chronisch: ouder dan een jaar en nog open.',
    acuut: 'Acuut',
    chronisch: 'Chronisch',
    kTop: 'Top 15 op risicoscore',
    uTop: 'Hoogste scores eerst; klik voor het detail.',
    kAfspraak: 'Dekking van actie-afspraken',
    uAfspraak: 'Open dependencies (niet gemitigeerd) met en zonder actie-afspraak, en gemitigeerde zonder beschreven mitigatie.',
    metAfspraak: 'Met actie-afspraak',
    zonderAfspraak: 'Zonder actie-afspraak',
    gemitigeerdZonder: 'Gemitigeerd zonder tekst',
    mitigatieZonderStatus: 'Mitigatietekst maar niet gemitigeerd',
    // verdelingen
    kNiveau: 'Per risiconiveau',
    kStatus: 'Per status',
    kScope: 'Per scope',
    kFlowtype: 'Per flowtype',
    kCategorie: 'Per categorie',
    kEffect: 'Per effect op de flow',
    uVerdeling: 'Aantal open dependencies.',
    kHotspots: 'Hotspots team × categorie',
    topVan: 'top {{n}} van {{total}}',
    uHotspots: 'Cellen met de meeste dependencies; factor = aantal gedeeld door het gemiddelde van alle gevulde cellen.',
    factor: 'factor',
    hoogste: 'hoogste',
    // concentratie
    kPartijen: 'Externe partijen als hub',
    uPartijen: 'Per partij uit het register of vrije naam: hoeveel teams en dependencies eraan hangen, plus input- en outputitems. Flowverlies = som van wachttijd × frequentie van die dependencies.',
    partij: 'Partij',
    type: 'Type',
    status: 'Status',
    teams: 'Teams',
    deps: 'Dependencies',
    blokkerend: 'Blokkerend',
    io: 'In/uit',
    flowverlies: 'Flowverlies',
    nietInRegister: 'niet in register',
    kTeamOpTeam: 'Wie blokkeert wie',
    uTeamOpTeam: 'Dependencies met een ander team als veroorzaker. Netto = veroorzaakt bij anderen min zelf ondervonden.',
    veroorzaker: 'Veroorzaker',
    getroffen: 'Getroffen',
    veroorzaakt: 'Veroorzaakt',
    ondervonden: 'Ondervonden',
    netto: 'Netto',
    kKennis: 'Kennisconcentratie en bus-factor',
    uKennis: 'Score = 2 × kennisdependencies met Hoog of Kritiek + overige kennisdependencies + capaciteitsrijen met risico bij uitval + applicaties met risico bij uitval.',
    kennisDeps: 'Kennis-deps',
    kennisHoog: 'waarvan Hoog+',
    risicoRijen: 'Rollen met uitvalrisico',
    appsRisico: 'Apps met uitvalrisico',
    senior: 'Senior',
    junior: 'Junior',
    score: 'Score',
    // keten
    kKetenTeams: 'Koppelingen per team',
    uKetenTeams: 'Geaccepteerde ketenkoppelingen: inkomend en uitgaand, en met hoeveel verschillende partners.',
    inkomend: 'Inkomend',
    uitgaand: 'Uitgaand',
    partners: 'Partners',
    kCycli: 'Cycli in de keten',
    uCycli: 'Teams die via koppelingen bij zichzelf terugkomen. Eén cyclus aan het eind is normaal; meer cycli maken de keten onleesbaar.',
    geenCycli: 'Geen cycli.',
    sigFilterErnst: 'Ernst',
    sigFilterSoort: 'Soort',
    sigFilterAlleSoorten: 'Alle soorten',
    sigFilterZoek: 'Zoek in de signalen…',
    sigAantal: '{{n}} van de {{total}} signalen',
    sigGeenNaFilter: 'Geen signaal voldoet aan deze filters.',
    sig_blokkerendVerouderd: 'Blokkerend en verouderd',
    sig_dubbeleRegistratie: 'Dubbele registratie',
    sig_geaccepteerdHoog: 'Geaccepteerd maar hoog risico',
    sig_gedeeldeApp: 'Gedeelde applicatie',
    sig_gemitigeerdNietGesloten: 'Gemitigeerd, niet gesloten',
    sig_hardeDeadlineZonderAfspraak: 'Deadline zonder afspraak',
    sig_heropend: 'Heropend',
    sig_hoogVerouderd: 'Hoog en verouderd',
    sig_kennisBusFactor: 'Kennisconcentratie',
    sig_ketenRisico: 'Hoog ketenrisico',
    sig_kritiekZonderAfspraak: 'Kritiek zonder afspraak',
    sig_langBlokkerend: 'Lang blokkerend',
    sig_partijGeweigerd: 'Partij geweigerd',
    sig_partijHub: 'Partij raakt veel teams',
    sig_reviewOud: 'Review blijft liggen',
    sig_slapendTeam: 'Slapend team',
    sig_sluimerend: 'Sluimerend',
    sig_spofZonderDetail: 'Kwetsbare applicatie zonder detail',
    sig_stilRisico: 'Stil risico',
    sig_teamVerouderd: 'Team met verouderde records',
    sig_teruggevallen: 'Teruggevallen',
    sig_verslechterd: 'Verslechterd',
    sig_verzoekOud: 'Koppelverzoek blijft liggen',
    sig_wederzijds: 'Wederzijdse afhankelijkheid',
    cycliAfgekapt: 'Meer dan {{n}} cycli gevonden; alleen de eerste {{n}} zijn doorzocht en worden hier getoond.',
    kLos: 'Losse inputs en onbenutte outputs',
    uLos: 'Inputs zonder koppeling of partij, en outputs die niemand afneemt. Niet fout, wel een teken van een onvolledige kaart.',
    losseInputs: 'Losse inputs',
    losseOutputs: 'Onbenutte outputs',
    kVerzoeken: 'Koppelingsverzoeken',
    uVerzoeken: 'Open verzoeken met hun leeftijd, afgewezen verzoeken, en de gemiddelde doorlooptijd van voorstel tot besluit.',
    afgewezen: 'Afgewezen',
    gemDoorlooptijd: 'Gemiddelde doorlooptijd van besluit',
    kMismatch: 'Kaart tegenover praktijk',
    uMismatch: 'Links: dependency op een team waarmee geen ketenkoppeling bestaat. Rechts: koppeling tussen teams zonder dependency in welke richting ook.',
    depZonderKoppeling: 'Dependency zonder koppeling',
    koppelingZonderDep: 'Koppeling zonder dependency',
    kSpof: 'Applicaties als single point of failure',
    uSpof: 'Risico bij uitval uit de applicatiedetails, en de last: dependencies + input/output-items + applicatiekoppelingen.',
    applicatie: 'Applicatie',
    uitval: 'Uitval',
    last: 'Last',
    // proces
    kWerkstappen: 'Belasting per werkstap',
    uWerkstappen: 'Ontwikkelflow-dependencies per stap, de top-effecten, en de capaciteit die teams op die stap hebben ingevuld.',
    stap: 'Werkstap',
    effecten: 'Top-effecten',
    personen: 'Personen',
    teamsMetCap: 'Teams met capaciteit',
    kProces: 'Hygiënegevallen in de flow',
    uProces: 'Ontwikkelflow zonder werkstap, applicatieflow zonder applicatie, dependencies over meerdere applicaties, en zonder flowtype.',
    zonderStap: 'Proces-overstijgend',
    appOverstijgend: 'Applicatie-overstijgend',
    multiApp: 'Meerdere applicaties',
    zonderFlowtype: 'Flowtype nog te bepalen',
    // flowverlies
    kFlowTeam: 'Flowverlies per team',
    kFlowCategorie: 'Flowverlies per categorie',
    kFlowPartij: 'Flowverlies per partij',
    uFlow: 'Som van wachttijd-punten × frequentie-punten van de open dependencies: een maat voor wat niets doen kost.',
    onvolledig: 'onvolledig',
    // doorloop
    kDoorloop: 'Oplostempo',
    uDoorloop: 'Dagen van aanmaak tot de eerste mitigatie en tot sluiting, uit de historie. Blokkerend = totale dagen in status actief blokkerend.',
    gemTotMitigatie: 'Gem. tot mitigatie',
    medTotMitigatie: 'Mediaan tot mitigatie',
    gemTotSluiting: 'Gem. tot sluiting',
    medTotSluiting: 'Mediaan tot sluiting',
    ooitBlokkerend: 'Ooit blokkerend',
    gemBlokkerend: 'Gem. dagen blokkerend',
    kDoorloopTeam: 'Oplostempo per team',
    gemitigeerd: 'Gemitigeerd',
    kLangstBlokkerend: 'Langst blokkerend (open)',
    uLangstBlokkerend: 'Open dependencies met de meeste dagen in status actief blokkerend.',
    kOoitBlokkerend: 'Escalatiegeschiedenis',
    uOoitBlokkerend: 'Dependencies die in hun historie een of meer keer naar actief blokkerend zijn gegaan.',
    // kwaliteit
    kScheef: 'Scheefstand in bestaande records',
    uScheef: 'Twee controles op wat er al staat: records zonder naam, en externe partijen die onder dezelfde vergelijkingsregel als het formulier dubbel voorkomen. Alleen gemeld, nooit automatisch opgeruimd — dat is een keuze per geval.',
    scheefGeen: 'Niets gevonden: elk record heeft een naam en geen twee externe partijen heten hetzelfde.',
    scheefNaamloos: 'Records zonder naam',
    scheefDubbel: 'Externe partijen die dubbel voorkomen',
    scheefZacht: 'Dit is geen kapotte data — de app werkt gewoon door.',
    scheefSoortTeam: 'team',
    scheefSoortDependency: 'dependency',
    scheefSoortPartij: 'externe partij',
    scheefSoortInput: 'input',
    scheefSoortOutput: 'output',
    scheefSoortApplicatie: 'applicatie',
    scheefSoortCapaciteit: 'capaciteitsregel',
    kChecks: 'Hygiënecontroles op dependencies',
    uChecks: 'Elke regel is een simpele check op velden; klik om de records te zien.',
    hFlowtype: 'Zonder flowtype',
    hProfiel: 'Profiel onvolledig (uitgebreide analyse)',
    hDeadlineTekst: 'Deadline zonder tekst',
    hCategorieScope: 'Categorie past niet bij scope',
    hExternZonderPartij: 'Ketenniveau zonder partij of team',
    hPartijOnbekend: 'Partij niet (meer) in register',
    hPartijGeweigerd: 'Partij geweigerd maar nog genoemd',
    hEffectLeeg: 'Effect op flow leeg',
    hGeenToelichting: 'Zonder toelichting',
    hDubbeleTitels: 'Zelfde titel bij meerdere teams',
    hVerouderd: 'Verouderd',
    hZonderAanmaak: 'Zonder aanmaakdatum',
    kIoChecks: 'Hygiënecontroles op input/output en applicaties',
    uIoChecks: 'Items met een onbekende applicatie of partij, items zonder flowtype, en applicaties zonder enige relatie.',
    ioAppOnbekend: 'Item verwijst naar onbekende applicatie',
    ioPartijOnbekend: 'Item verwijst naar onbekende partij',
    ioZonderFlowtype: 'Item zonder flowtype',
    appsZonderRelatie: 'Applicaties zonder relatie',
    // beheer
    kRegistratie: 'Registratie per week',
    uRegistratie: 'Gebeurtenissen uit de wijzigingenlog: aangemaakt, gewijzigd, gesloten en koppelingsverzoeken.',
    aangemaakt: 'Aangemaakt',
    gewijzigd: 'Gewijzigd',
    koppelingen: 'Koppelingen',
    kRegistratieTeam: 'Activiteit per team (90 dagen)',
    uRegistratieTeam: 'Wie registreert en onderhoudt zijn dependencies, en wie niet.',
    kReview: 'Review-wachtrij',
    uReview: 'Aanmeldingen die op goedkeuring wachten in de admin-log, met leeftijd. Plus het aantal duplicaatmeldingen ooit.',
    duplicaten: 'Duplicaatmeldingen',
    logTotaal: 'Logregels totaal',
  },
  en: {
    titel: 'Analysis',
    intro: 'Everything below comes straight from the data in this tool and every card explains its own rule. Trends and lead times come from the change history of the dependencies.',
    alleTeams: 'All teams',
    teamFilter: 'Team',
    periode: 'Period',
    weken: '{{n}} weeks',
    vsToen: 'vs. 30 days ago',
    geenData: 'No data.',
    toon: 'Show {{n}} records',
    verberg: 'Hide',
    dagen: '{{n}} days',
    dag: 'days',
    team: 'Team',
    titelKol: 'Title',
    risico: 'Risk',
    aantal: 'Count',
    gesloten: 'closed',
    geslotenKop: 'Closed',
    categorie: 'Category',
    escalatie: '{{n}} escalation',
    escalatiesN: '{{n}} escalations',
    kindInput: 'Input',
    kindOutput: 'Output',
    sRapport: 'Report',
    sWaarschuwingen: 'Warnings',
    rapportUitleg: 'Running text from the same numbers: summary, development, risk, teams, chain, applications, data quality and recommendations. Follows the team filter.',
    rapportKopieer: 'Copy report',
    rapportDownload: 'Download',
    rapportDownloadTitel: 'Download the report as a markdown file',
    rapportGekopieerd: 'Copied',
    rapportTitel: 'Dependency report',
    waarschuwingenUitleg: 'One sentence per case, sorted by severity and weight. Click to open the detail or the team page.',
    waarschuwingenGeen: 'No warnings.',
    toonAlle: 'Show all {{n}}',
    toonMinder: 'Show fewer',
    navTabs: 'Sections',
    tabOverzicht: 'Overview',
    tabSignalen: 'Signals',
    tabTrends: 'Trends',
    tabRisico: 'Risk',
    tabKeten: 'Chain and process',
    tabData: 'Data and administration',
    cVerslechterd: 'Rose to High or Critical in 30 days',
    cTeruggevallen: 'Mitigation did not hold',
    cSluimerend: 'Dormant: high or critical, older than six months, without agreement',
    cGeaccepteerdHoog: 'Parked (accepted) but High or Critical',
    cGemitigeerdNietGesloten: 'Mitigated for more than 90 days but not closed',
    cHeropend: 'Reopened after closure',
    cBacklogGroei: 'The backlog is growing: more new than closed',
    cKetenRisicoHoog: 'Much blocking or high risk at direct suppliers: {{teams}}',
    cWederzijds: 'Mutual dependency between teams: {{paren}}',
    cGedeeldeApp: 'Application linked to several other teams via the chain: {{apps}}',
    cSlapendTeam: 'Nothing registered for 60 days: {{teams}}',
    cDubbeleRegistratie: 'Same dependency registered separately by several teams',
    kVerandering: 'Worsened and improved (30 days)',
    uVerandering: 'Score of 30 days ago (replay) against now; only dependencies that existed then.',
    verslechterd: 'Worsened',
    verbeterd: 'Improved',
    kProjectie: 'Projection',
    uProjectie: 'Linear extrapolation of the last 13 weeks: average new and closed per week. No model, only pace.',
    pNieuwPerWeek: 'New per week',
    pGeslotenPerWeek: 'Closed per week',
    pNetto: 'Net per week',
    pOverHorizon: 'Open in 13 weeks',
    pWekenTotLeeg: 'Weeks until backlog empty',
    kOvergangen: 'Status transitions',
    uOvergangen: 'All status changes from the history, from and to. Below: mitigations that did not hold and reopenings.',
    van: 'From',
    naar: 'To',
    teruggevallen: 'Mitigation did not hold',
    heropend: 'Reopened',
    kLeeftijd: 'Age distribution',
    uLeeftijd: 'Days since creation of the open dependencies, in classes; average and median per team.',
    gemiddeld: 'Avg.',
    mediaan: 'Median',
    totaal: 'Total',
    kLevensloop: 'Dormant, parked and not closed',
    uLevensloop: 'Dormant: known risk at High or Critical, older than 180 days, without agreement. Parked: accepted but High or Critical. Not closed: mitigated for more than 90 days.',
    sluimerend: 'Dormant',
    geparkeerdHoog: 'Parked but high',
    nietAfgesloten: 'Mitigated, not closed',
    kScorekaart: 'Team scorecard',
    uScorekaart: 'All teams side by side, regardless of the team filter; the bottom row is the average per team. Δ30 = change in open dependencies vs. 30 days ago.',
    open: 'Open',
    hoogPlus: 'High+',
    kritiekKort: 'Critical',
    gemScoreKort: 'Avg. score',
    verouderdPct: 'Stale',
    afspraakPct: 'With agreement',
    delta30: 'Δ30',
    gesloten90: 'Closed 90d',
    kennisScore: 'Knowledge',
    gemiddeldPerTeam: 'Average per team',
    kPareto: 'Concentration (top 3)',
    uPareto: 'The share the three largest account for, and the largest category per team.',
    top3Partijen: 'Parties',
    top3Categorieen: 'Categories',
    top3Teams: 'Teams',
    topCategoriePerTeam: 'Largest category per team',
    vanTotaal: 'of {{n}}',
    kKetenRisico: 'Chain risk upstream and downstream',
    uKetenRisico: 'Via accepted links: from how many teams a team receives input (direct and beyond), how many blocking and high dependencies those direct suppliers (S) have open, and how many teams it affects downstream itself. Confirmed = own dependencies naming such a supplier as the cause.',
    direct: 'Direct',
    stroomop: 'Upstream',
    stroomaf: 'Downstream',
    blokTL: 'Blocking at S',
    hoogTL: 'High+ at S',
    bevestigd: 'Confirmed',
    kWederzijds: 'Mutual dependencies',
    uWederzijds: 'Team pairs that registered dependencies on each other.',
    geenWederzijds: 'No mutual dependencies.',
    kKaart: 'Map completeness per team',
    uKaart: 'Inputs explained (link or party), outputs consumed or external, applications with outage risk filled in, links with points. Completeness = average of those percentages.',
    inputsVerklaard: 'Inputs explained',
    outputsVerklaard: 'Outputs explained',
    appsDetail: 'Apps with detail',
    koppelingenPunten: 'Links with points',
    notities: 'Notes',
    volledigheid: 'Completeness',
    kGedeeld: 'Shared applications',
    uGedeeld: 'Applications that hang on other teams through an accepted chain link (output with application to input with application), with their own dependencies.',
    andereTeams: 'Other teams',
    geenGedeeld: 'No applications with chain links to other teams.',
    kSlapend: 'Last activity per team',
    uSlapend: 'Last log entry per team; more than 60 days quiet counts as dormant.',
    laatsteActiviteit: 'Last activity',
    dagenStil: 'Days quiet',
    slapend: 'Dormant',
    kDuplicaten: 'Duplicate registrations',
    uDuplicaten: 'Groups of dependencies registered separately by more than one team (dedup group).',
    geenDuplicaten: 'No duplicate registrations.',
    nooit: 'never',
    sOverzicht: 'Overview',
    sConstateringen: 'Findings',
    sTrends: 'Trends',
    sRisico: 'Risk and urgency',
    sVerdeling: 'Distributions and hotspots',
    sConcentratie: 'Concentration and hubs',
    sKeten: 'Chain',
    sProces: 'Applications and development process',
    sFlowverlies: 'Flow loss',
    sDoorloop: 'Lead times',
    sKwaliteit: 'Data quality',
    sBeheer: 'Administration and registration',
    tOpen: 'Open dependencies',
    tKritiek: 'Critical',
    tHoog: 'High or critical',
    tBlokkerend: 'Actively blocking',
    tVerouderd: 'Stale (>90 days without update)',
    tAfspraak: 'Open without action agreement',
    tGeaccepteerd: 'Accepted (parked)',
    tGesloten90: 'Closed in the last 90 days',
    tNieuw30: 'New in the last 30 days',
    tMitigatie: 'Avg. days to mitigation',
    tScore: 'Average risk score',
    tVerzoeken: 'Open link requests',
    ernstHoog: 'high',
    ernstMidden: 'medium',
    ernstLaag: 'low',
    cKritiekZonderAfspraak: 'Critical dependencies without an action agreement',
    cHardeDeadlineZonderAfspraak: 'Hard deadline without an action agreement',
    cBlokkerendVerouderd: 'Actively blocking but not updated for more than 90 days',
    cLangBlokkerend: 'Blocking for more than 60 days without interruption',
    cHoogVerouderd: 'High risk, no action agreement and stale',
    cStilRisico: 'Silent risks: low or medium risk but high flow loss',
    cPartijGeweigerd: 'Reference to a rejected party',
    cPartijInAfwachting: 'Reference to a party that has not been approved yet',
    cPartijHub: 'Party touches half of the teams or more: {{partijen}}',
    cVerzoekOud: 'Link requests open for more than two weeks',
    cDepZonderKoppeling: 'Dependency on a team without a chain link to that team',
    cSpofZonderDetail: 'Heavily loaded application without a filled-in outage risk: {{apps}}',
    cTeamVerouderd: 'More than 40% of dependencies stale at: {{teams}}',
    cKennisBusFactor: 'High-risk knowledge concentration at: {{teams}}',
    cFaseZonderCapaciteit: 'Workflow step with dependencies but no capacity: {{fasen}}',
    cReviewOud: 'Registrations waiting for review for more than a week',
    cGemitigeerdZonderTekst: 'Mitigated without a described mitigation',
    cProfielOnvolledig: 'Profile incomplete (waiting time, deadline or solvability empty)',
    cGeen: 'No findings. All rules are clean.',
    kOpenStatus: 'Open dependencies per status',
    uOpenStatus: 'State per week, replayed from the history: a dependency counts from creation to closure, with the status of that moment.',
    kOpenNiveau: 'Open dependencies per risk level',
    uOpenNiveau: 'Same replay, but with the risk score of that moment (impact × frequency + status correction).',
    kNieuwGesloten: 'New and closed per week',
    uNieuwGesloten: 'Creation and closure dates per week. More new than closed means a growing backlog.',
    kScore: 'Sum of risk scores',
    uScore: 'All open scores added up: one number for the total risk pressure.',
    kKwadranten: 'Quadrants: flow loss against solvability',
    uKwadranten: 'Quick win = much loss, solvable by the team. Escalate = much loss, outside the team. Clean up = little loss, solvable by the team. Accept = little loss, outside the team.',
    qQuickWin: 'Quick wins',
    qOpschalen: 'Escalate',
    qOpruimen: 'Clean up',
    qAccepteren: 'Accept',
    qOnvolledig: 'Profile incomplete',
    kStil: 'Silent risks',
    uStil: 'Risk Low or Medium, flow loss High or Critical. Exactly the list the risk score does not put on top.',
    kQuick: 'Quick wins',
    uQuick: 'Solvable by one or more team members and flow loss at least Medium.',
    kDeadlines: 'Deadlines',
    uDeadlines: 'Fixed and hard deadlines, hard first. Red marker: no action agreement.',
    kGemitigeerdHoog: 'Mitigated but still High',
    uGemitigeerdHoog: 'The base (impact × frequency) stays heavy, even with the minus 2 correction.',
    kAcuut: 'Acute and chronic',
    uAcuut: 'Acute: created in the last 30 days. Chronic: older than a year and still open.',
    acuut: 'Acute',
    chronisch: 'Chronic',
    kTop: 'Top 15 by risk score',
    uTop: 'Highest scores first; click for the detail.',
    kAfspraak: 'Coverage of action agreements',
    uAfspraak: 'Open dependencies (not mitigated) with and without an action agreement, and mitigated ones without a described mitigation.',
    metAfspraak: 'With action agreement',
    zonderAfspraak: 'Without action agreement',
    gemitigeerdZonder: 'Mitigated without text',
    mitigatieZonderStatus: 'Mitigation text but not mitigated',
    kNiveau: 'Per risk level',
    kStatus: 'Per status',
    kScope: 'Per scope',
    kFlowtype: 'Per flow type',
    kCategorie: 'Per category',
    kEffect: 'Per effect on the flow',
    uVerdeling: 'Number of open dependencies.',
    kHotspots: 'Hotspots team × category',
    topVan: 'top {{n}} of {{total}}',
    uHotspots: 'Cells with the most dependencies; factor = count divided by the average of all filled cells.',
    factor: 'factor',
    hoogste: 'highest',
    kPartijen: 'External parties as hubs',
    uPartijen: 'Per party from the register or free text: how many teams and dependencies hang on it, plus input and output items. Flow loss = sum of waiting time × frequency of those dependencies.',
    partij: 'Party',
    type: 'Type',
    status: 'Status',
    teams: 'Teams',
    deps: 'Dependencies',
    blokkerend: 'Blocking',
    io: 'In/out',
    flowverlies: 'Flow loss',
    nietInRegister: 'not in register',
    kTeamOpTeam: 'Who blocks whom',
    uTeamOpTeam: 'Dependencies with another team as the cause. Net = caused at others minus experienced.',
    veroorzaker: 'Cause',
    getroffen: 'Affected',
    veroorzaakt: 'Caused',
    ondervonden: 'Experienced',
    netto: 'Net',
    kKennis: 'Knowledge concentration and bus factor',
    uKennis: 'Score = 2 × knowledge dependencies at High or Critical + other knowledge dependencies + capacity rows with outage risk + applications with outage risk.',
    kennisDeps: 'Knowledge deps',
    kennisHoog: 'of which High+',
    risicoRijen: 'Roles with outage risk',
    appsRisico: 'Apps with outage risk',
    senior: 'Senior',
    junior: 'Junior',
    score: 'Score',
    kKetenTeams: 'Links per team',
    uKetenTeams: 'Accepted chain links: incoming and outgoing, and with how many different partners.',
    inkomend: 'Incoming',
    uitgaand: 'Outgoing',
    partners: 'Partners',
    kCycli: 'Cycles in the chain',
    uCycli: 'Teams that come back to themselves via links. One cycle at the end is normal; more cycles make the chain unreadable.',
    geenCycli: 'No cycles.',
    sigFilterErnst: 'Severity',
    sigFilterSoort: 'Type',
    sigFilterAlleSoorten: 'All types',
    sigFilterZoek: 'Search the signals…',
    sigAantal: '{{n}} of {{total}} signals',
    sigGeenNaFilter: 'No signal matches these filters.',
    sig_blokkerendVerouderd: 'Blocking and stale',
    sig_dubbeleRegistratie: 'Duplicate registration',
    sig_geaccepteerdHoog: 'Accepted but high risk',
    sig_gedeeldeApp: 'Shared application',
    sig_gemitigeerdNietGesloten: 'Mitigated, not closed',
    sig_hardeDeadlineZonderAfspraak: 'Deadline without agreement',
    sig_heropend: 'Reopened',
    sig_hoogVerouderd: 'High and stale',
    sig_kennisBusFactor: 'Knowledge concentration',
    sig_ketenRisico: 'High chain risk',
    sig_kritiekZonderAfspraak: 'Critical without agreement',
    sig_langBlokkerend: 'Blocking for a long time',
    sig_partijGeweigerd: 'Party rejected',
    sig_partijHub: 'Party touches many teams',
    sig_reviewOud: 'Review left waiting',
    sig_slapendTeam: 'Dormant team',
    sig_sluimerend: 'Simmering',
    sig_spofZonderDetail: 'Vulnerable application without detail',
    sig_stilRisico: 'Silent risk',
    sig_teamVerouderd: 'Team with stale records',
    sig_teruggevallen: 'Fallen back',
    sig_verslechterd: 'Worsened',
    sig_verzoekOud: 'Link request left waiting',
    sig_wederzijds: 'Mutual dependency',
    cycliAfgekapt: 'More than {{n}} cycles found; only the first {{n}} were searched and are shown here.',
    kLos: 'Loose inputs and unused outputs',
    uLos: 'Inputs without link or party, and outputs nobody consumes. Not wrong, but a sign of an incomplete map.',
    losseInputs: 'Loose inputs',
    losseOutputs: 'Unused outputs',
    kVerzoeken: 'Link requests',
    uVerzoeken: 'Open requests with their age, rejected requests, and the average lead time from proposal to decision.',
    afgewezen: 'Rejected',
    gemDoorlooptijd: 'Average decision lead time',
    kMismatch: 'Map versus practice',
    uMismatch: 'Left: dependency on a team without a chain link to it. Right: link between teams without a dependency in either direction.',
    depZonderKoppeling: 'Dependency without link',
    koppelingZonderDep: 'Link without dependency',
    kSpof: 'Applications as single point of failure',
    uSpof: 'Outage risk from the application details, and the load: dependencies + input/output items + application links.',
    applicatie: 'Application',
    uitval: 'Outage',
    last: 'Load',
    kWerkstappen: 'Load per workflow step',
    uWerkstappen: 'Development-flow dependencies per step, the top effects, and the capacity teams have filled in for that step.',
    stap: 'Step',
    effecten: 'Top effects',
    personen: 'People',
    teamsMetCap: 'Teams with capacity',
    kProces: 'Hygiene cases in the flow',
    uProces: 'Development flow without step, application flow without application, dependencies across several applications, and without flow type.',
    zonderStap: 'Process-wide',
    appOverstijgend: 'Application-wide',
    multiApp: 'Multiple applications',
    zonderFlowtype: 'Flow type to be determined',
    kFlowTeam: 'Flow loss per team',
    kFlowCategorie: 'Flow loss per category',
    kFlowPartij: 'Flow loss per party',
    uFlow: 'Sum of waiting-time points × frequency points of the open dependencies: a measure of what doing nothing costs.',
    onvolledig: 'incomplete',
    kDoorloop: 'Resolution pace',
    uDoorloop: 'Days from creation to the first mitigation and to closure, from the history. Blocking = total days in status actively blocking.',
    gemTotMitigatie: 'Avg. to mitigation',
    medTotMitigatie: 'Median to mitigation',
    gemTotSluiting: 'Avg. to closure',
    medTotSluiting: 'Median to closure',
    ooitBlokkerend: 'Ever blocking',
    gemBlokkerend: 'Avg. days blocking',
    kDoorloopTeam: 'Resolution pace per team',
    gemitigeerd: 'Mitigated',
    kLangstBlokkerend: 'Longest blocking (open)',
    uLangstBlokkerend: 'Open dependencies with the most days in status actively blocking.',
    kOoitBlokkerend: 'Escalation history',
    uOoitBlokkerend: 'Dependencies that went to actively blocking one or more times in their history.',
    kScheef: 'Drift in existing records',
    uScheef: 'Two checks on what is already there: records without a name, and external parties that appear twice under the same comparison rule the form uses. Reported only, never cleaned up automatically — that is a case-by-case choice.',
    scheefGeen: 'Nothing found: every record has a name and no two external parties share one.',
    scheefNaamloos: 'Records without a name',
    scheefDubbel: 'External parties appearing twice',
    scheefZacht: 'This is not broken data — the app keeps working.',
    scheefSoortTeam: 'team',
    scheefSoortDependency: 'dependency',
    scheefSoortPartij: 'external party',
    scheefSoortInput: 'input',
    scheefSoortOutput: 'output',
    scheefSoortApplicatie: 'application',
    scheefSoortCapaciteit: 'capacity row',
    kChecks: 'Hygiene checks on dependencies',
    uChecks: 'Each rule is a simple field check; click to see the records.',
    hFlowtype: 'Without flow type',
    hProfiel: 'Profile incomplete (extended analysis)',
    hDeadlineTekst: 'Deadline without text',
    hCategorieScope: 'Category does not match scope',
    hExternZonderPartij: 'Chain level without party or team',
    hPartijOnbekend: 'Party no longer in register',
    hPartijGeweigerd: 'Party rejected but still referenced',
    hEffectLeeg: 'Effect on flow empty',
    hGeenToelichting: 'Without explanation',
    hDubbeleTitels: 'Same title at several teams',
    hVerouderd: 'Stale',
    hZonderAanmaak: 'Without creation date',
    kIoChecks: 'Hygiene checks on input/output and applications',
    uIoChecks: 'Items with an unknown application or party, items without flow type, and applications without any relation.',
    ioAppOnbekend: 'Item refers to unknown application',
    ioPartijOnbekend: 'Item refers to unknown party',
    ioZonderFlowtype: 'Item without flow type',
    appsZonderRelatie: 'Applications without relation',
    kRegistratie: 'Registration per week',
    uRegistratie: 'Events from the change log: created, updated, closed and link requests.',
    aangemaakt: 'Created',
    gewijzigd: 'Updated',
    koppelingen: 'Links',
    kRegistratieTeam: 'Activity per team (90 days)',
    uRegistratieTeam: 'Who registers and maintains their dependencies, and who does not.',
    kReview: 'Review queue',
    uReview: 'Registrations waiting for approval in the admin log, with age. Plus the number of duplicate warnings ever.',
    duplicaten: 'Duplicate warnings',
    logTotaal: 'Log entries total',
  },
}

export const STATUS_KLEUR = { 'bekend risico': '#5c6b8a', 'actief blokkerend': '#9a3b2e', gemitigeerd: '#5c8a72' }
// Ernst volgt de warme ordinale risicoreeks (geen stoplichtkleuren).
export const ERNST_STIJL = {
  hoog: 'bg-[#c1552c]/[0.12] text-[#8a3b1c] border-[#c1552c]/40',
  midden: 'bg-[#b8842c]/[0.14] text-[#7a5a1a] border-[#b8842c]/40',
  laag: 'bg-slate-100 text-slate-600 border-slate-300',
}
export const WARM = '#b8842c'

export function vul(sjabloon, vars) {
  if (!vars) return sjabloon
  return sjabloon.replace(/\{\{(\w+)\}\}/g, (_, k) => (vars[k] ?? ''))
}

// --- bouwstenen ---------------------------------------------------------

