import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.waitForSelector('text=Dependency Insight')
  await page.click('text=Matrix-overzicht')
})

test('nieuwe dependency met alle optionele velden wordt correct opgeslagen', async ({ page }) => {
  await page.click('button:has-text("+ Nieuwe dependency")')
  await page.waitForSelector('text=Nieuwe dependency')
  const modal = page.locator('.fixed.inset-0.z-50')
  const sel = (i) => modal.locator('select').nth(i)

  await sel(0).selectOption({ label: 'Team Equinox' })
  await sel(1).selectOption({ label: 'Kennis-concentratie' })
  await page.fill('input[placeholder*="Kennis legacy-betaalsysteem"]', 'E2E test dependency')
  await page.fill('input[placeholder*="Senior developer"]', 'E2E tester (1 persoon)')
  await sel(2).selectOption('hoog')
  await sel(3).selectOption('vaak')
  await sel(4).selectOption('actief blokkerend')
  await sel(5).selectOption('testen')
  await sel(6).selectOption('systeem')
  await sel(7).selectOption('vertraging')
  await sel(8).selectOption('nee')
  await page.fill('textarea[placeholder*="Wat wordt er al aan gedaan"]', 'E2E mitigatie')
  await page.click('button:has-text("Opslaan")')
  await page.waitForTimeout(300)

  await expect(page.locator('h3:has-text("Nieuwe dependency")')).toHaveCount(0)

  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('dependency-insight:v1')))
  const dep = stored.dependencies.find((d) => d.titel === 'E2E test dependency')
  expect(dep).toBeTruthy()
  expect(dep.impact).toBe('hoog')
  expect(dep.frequentie).toBe('vaak')
  expect(dep.status).toBe('actief blokkerend')
  expect(dep.workflow_fase).toBe('testen')
  expect(dep.bron_type).toBe('systeem')
  expect(dep.effect_op_flow).toBe('vertraging')
  expect(dep.zelf_oplosbaar).toBe('nee')
  expect(dep.mitigatie).toBe('E2E mitigatie')
})

test('dependency bewerken en verwijderen', async ({ page }) => {
  await page.click('button:has-text("+ Nieuwe dependency")')
  await page.waitForSelector('text=Nieuwe dependency')
  const modal = page.locator('.fixed.inset-0.z-50')
  await modal.locator('select').nth(0).selectOption({ label: 'Team Equinox' })
  await modal.locator('select').nth(1).selectOption({ label: 'Kennis-concentratie' })
  await page.fill('input[placeholder*="Kennis legacy-betaalsysteem"]', 'E2E edit dependency')
  await page.fill('input[placeholder*="Senior developer"]', 'E2E tester')
  await modal.locator('select').nth(2).selectOption('midden')
  await modal.locator('select').nth(3).selectOption('soms')
  await modal.locator('select').nth(4).selectOption('bekend risico')
  await page.click('button:has-text("Opslaan")')
  await page.waitForTimeout(300)

  await page.click('text=E2E edit dependency')
  await expect(page.locator('text=Risicoberekening')).toBeVisible()
  await page.click('button:has-text("Bewerken")')
  await page.waitForSelector('text=Dependency bewerken')
  await page.fill('input[placeholder*="Kennis legacy-betaalsysteem"]', 'E2E edit dependency BEWERKT')
  await page.click('button:has-text("Opslaan")')
  await page.waitForTimeout(300)

  let stored = await page.evaluate(() => JSON.parse(localStorage.getItem('dependency-insight:v1')))
  expect(stored.dependencies.some((d) => d.titel === 'E2E edit dependency BEWERKT')).toBe(true)

  await page.click('text=E2E edit dependency BEWERKT')
  await page.waitForTimeout(200)
  page.once('dialog', (d) => d.accept())
  await page.click('button:has-text("Verwijderen")')
  await page.waitForTimeout(300)

  stored = await page.evaluate(() => JSON.parse(localStorage.getItem('dependency-insight:v1')))
  expect(stored.dependencies.some((d) => d.titel === 'E2E edit dependency BEWERKT')).toBe(false)
})

test('nieuwe categorie toevoegen wordt meteen geselecteerd en overal beschikbaar', async ({ page }) => {
  await page.click('button:has-text("+ Nieuwe dependency")')
  await page.waitForSelector('text=Nieuwe dependency')
  const modal = page.locator('.fixed.inset-0.z-50')
  await modal.locator('select').nth(1).selectOption({ label: '+ Nieuwe categorie toevoegen' })
  await page.waitForSelector('input[placeholder="Naam nieuwe categorie"]')
  await page.fill('input[placeholder="Naam nieuwe categorie"]', 'E2E Custom Categorie')
  await modal.getByRole('button', { name: 'Toevoegen', exact: true }).click()
  await page.waitForTimeout(200)
  await expect(modal.locator('select').nth(1)).toHaveValue('E2E Custom Categorie')
})
